# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KN6efEf9Bn3K5rdRcl3fZzN3M+WV+HYcfJj+BGnlTumJBZp0xTtHZPomVLjna3VrrlpoqxXZIV5rrpWKPjZq1ZT0gk3oM24RxOQzec3vYGngsh6grB97JTXdc2asNyIbwk1rX6fZAR5V7n29S8Ato+pJdVwumq32bjYzyXa1f0geXKFbvw6V42n2ATcFDvGcNO9qkC4p/fWzqJc/4HqI/ySHFF2rWRstLH3ikwLInty4ynNUwAWvImZuzaH6qu1nIbRkR82OW3Hx/RkL0L+0LaobOB45eGhpZ60viIzfXYgA/cdMuRfq8LK4XwIhGVVLi+PJMnXY9wBaaj8GFGhyd4box64wsrHrmLcqWExX2FzLnrJ8g9kUuFba/K5N9EqBVrUrqzQmpP/bzgyCl9+KNYok5td2BaJqMXeGD5V/Vk3NuTZ07J+10gkJtCoL2wpUhnVVf8uHPC3RfiNAmGhnEgdELeSJbrsWWP9lv6pYDHk97y8/+CPENXlmEmWSbQCrQXgudf3we23plKUINwkyKIfFARoj6sn9oTxiMbnDsnnI0NUiMrqS9fpZixgei6qOemEuCfQgkUZZ9j8CxVLWmLFbUvXOmcIPAGjskR8S3FztgB+RFAov7Xvz/lcqMn9pClV5lj/H5SN92EgEtJMS+2U6ectHV0QByNbc8fMzYQ0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
