travis:
  secure:
    BINSTAR_TOKEN: UxGjmtb+k1F++nyOgdnK93EVEAkSfWj+qhxLqWesbMbxYNnqdzDHmUrhrwbPkPAjzOqDyLZGKcYW9qd+Ntos2USb6KEovSS6pqjWJM8AtwF9mrdamMpxlspDY8CoH3gJL9Ds09pPa5sr1eViAxLsf1neoEFo/rG9/rq8/Wt0qvBb7Bafo0rEZ4R4PfRtibGLs2M+eINKPE3N+eUpQq3UW0S32G9A6yedQgQ4AtSaWfKNGRdV3iKWIhQjQ0gBp3bu+kajuGqdNp1+kRu6r/dK4iyImSqZG7bXby3p/SQP5IO6G4JZcOjTB1gT7LrSctZ/mgyYRs5G6JXT6rExV2RFtzCzNKWnBiuZ6Tldgn1gFD8HaCSe5ckfuR6foVkLwxu+NvUkYXRPx17AkhjmHXNv8i5VLhxfQLX6fdzTZ2uKCiqg59KH1wDGrnQcC/2pTfkfnGxolGgR5j7H/jF/qEAgWCf8jVwF8iZ3WtsSSVKUzA2x+FN/SZe1mLkl1RjUVBfBSoUkGyeixamZpE6CME6wDhZEEiSo6waicOqqvuJZ/Hxzx5KgL8Z0VoB/udyP9GoeB+snCCHSoVpt1sDRXyiwn5reTrmzXLZql4pUBBwouGlminEACzJ66Aa4eGBE9zrr8M/P2s+wqjNkdkHU4hpZ72Iq+ZY2W1Y8sqyqd0BG6yM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
