travis:
  secure:
    BINSTAR_TOKEN: fT1W0AD4SP+W4o4bjuIbVZPnC3Ui6MukHPFPpHxnkqPzR8FCqBlsurZSwfEAKWMsAHjF1aS2BHDkZ7SFb+N52A7KtI5rJOHaWACB1ERQMlpQhI6sDMX91FGzOWvWOHO7xR6KWm0lWb4jWGbfr4Lz+Vt4mg0usl6RbMh9GM8URdn3EvBwX93Y4QQgmrgYuqL16F3VRShziMeuCB6DIscWDFfeWLxEtRaka2rrWzgMlDumoVu7LERsoC2+06FJmvXp29pzNsAXXfRrqLXnbBuBHfAYR+n3e3b1U14L4tTijrlTQuTA3IjW+uV4ECKawVRxZYHt+6rUer2e1tY2h0f3po6HRYbZDKMLuLvYwdhAbV9lO/DphTiaJ1KqjpRUCfkMW7mo8KmENcBoL+M07YA3gMrrBqW2bp3ZWyu/oLxy8q1uC6nL8o1SIL4wcCPITU2tHRuRbj9eDy3haFq+Kfd624PG2LxHf65kr5laym6ohs+tkpl3GUYwNY/eLs7oEcpBJp+oPesRGyHuzPmWTTjjeKYRJJ0Dsji07FHIjJ6vYJrhRtqLEde2UlOEOrUxnXmYHJ8QwfA6ynSJUgm4s75BGQY6Z9EzUDJETs5efHi8YhNnv1zusABKCH8HoLrgMts7mMxozDTuOdwEhBGIaFilkPKEkP9Vb8rgXi2En3Qm7gQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
